name: Release

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'

env:
  IMAGE: query-initializer

jobs:
  setup-build-publish-deploy:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - uses: marceloprado/has-changed-path@v1
        id: changed
        with:
          paths: src config

      - name: Add VERSION env property with commit short sha
        run: echo "VERSION=rev-$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: onfinality
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Build and push"
        uses: docker/build-push-action@v2
        if: steps.changed.outputs.changed == 'true'
        with:
          push: true
          file: ./Dockerfile
          tags: onfinality/${{env.IMAGE}}:${{env.VERSION}}
